language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: a/+CVUjUh0Ji4UrP6k2DO6RBKl8AU9Fuu4A6f3I8tK+eUkfJZhiaRXxHWj0XBhIS8nw5S+mxWuOt+IHYUDKFHYmP2Y9dlfawrzHXQQmD7gP6kOwflvWxwBMLzp5hm7DO4hMYEisGVoY9MsLWMXJ81S07NCobcEn3jNk5qBlDUQzor0G/dSiZwfNPitOKVPpveD6rrtqa0KGWlG41bWeuFOhqWsiqN2aOtHdQQQmI3ByhSLlfXdBOUDOI+OuItzpHR2bP2siFpgchvYWaGwlgWMgdG/S/6Kmafp4iWZ5Laoe2VpRBPOUikzJMFCdDNQLPOTsWeCuUP6WYbqO5DNpr2eLamAiCGMV8NkM9+KctHM9IAC9K3IdHF9sdvb1K/D6ZVVurZV2HNNVl9EFgw9rqm1DaSayg9SLXXRGLWZXvi+O0t9litgvIlbGW19pUwL9tjnuzPgXzs14CkHwArxzE8qUaumRSMQkj9i0sZMVDT+uL5rJG/r/+jtuQSo/CPzkaSaUvxIZPzgzLCG1ejItdWWgl8z5FXxmhj/2nfzUlc/Gp2C9E8KUx0Iin8o1UlBkHleqTFFJIz7yIM/fpwj2adW097AwOOq6rBwWrwa6sJuqVl9uD3PtA6hB8pSdQuBGPnx6eWHbQr6kM0Gin57SufJeOtTIRRAq9F9P3vI3bgh8=
  file: target/*.war
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
